#!/usr/bin/env python
"""
convert_to_tribunal.py
======================
Converts the JSON output from mod_sweep.py into the .jsonl format 
expected by the Tribunal judge.
"""

import argparse
import glob
import json
import os

def convert_sweep_to_tribunal_jsonl(input_dir: str, output_dir: str):
    os.makedirs(output_dir, exist_ok=True)
    
    # Find all JSON files generated by mod_sweep.py
    json_files = glob.glob(os.path.join(input_dir, "mod_sweep_*.json"))
    
    if not json_files:
        print(f"No JSON files found in {input_dir}. Check your input directory.")
        return

    for json_file in json_files:
        filename = os.path.basename(json_file)
        
        # Extract the config tag to use as the model_id (e.g., "h1.00_u0.00")
        model_name = filename.replace("mod_sweep_", "").replace(".json", "")
        output_file = os.path.join(output_dir, f"{model_name}.jsonl")
        
        with open(json_file, 'r', encoding='utf-8') as f:
            try:
                data = json.load(f)
            except json.JSONDecodeError:
                print(f"Warning: Could not parse {filename}. Skipping.")
                continue
            
        with open(output_file, 'w', encoding='utf-8') as out_f:
            for idx, record in enumerate(data):
                # Standardize the schema exactly to the requested format
                jsonl_record = {
                    "id": idx,
                    "prompt": record["prompt"],
                    "response": record["response"]
                }
                
                # Write as a single JSON line
                out_f.write(json.dumps(jsonl_record, ensure_ascii=False) + "\n")
                
        print(f"✅ Converted {filename} -> {os.path.basename(output_file)} ({len(data)} records)")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert mod_sweep JSON outputs to Tribunal JSONL")
    parser.add_argument("--input", "-i", type=str, default="./sweep_outputs", 
                        help="Directory containing mod_sweep_*.json files")
    parser.add_argument("--output", "-o", type=str, default="./tribunal_inputs", 
                        help="Directory to save the converted .jsonl files")
    
    args = parser.parse_args()
    convert_sweep_to_tribunal_jsonl(args.input, args.output)
    
    print(f"\nDone. You can now pass '{args.output}' to tribunal.run_eval")